name: Build

on: [ workflow_call, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: "Setup dotnet"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: "Build"
        run: |
          dotnet build \
            -p:UnityEditor=/home/runner/work/Entitas/Entitas/unity/Unity-2021.3.0f1/UnityEditor.dll \
            -p:UnityEngine=/home/runner/work/Entitas/Entitas/unity/Unity-2021.3.0f1/UnityEngine.dll \
            -c Release

      - name: "Publish"
        run: dotnet publish -c Release --no-build -p:UseAppHost=false -o dist/Assemblies

      - name: "Upload assemblies"
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }} Assemblies
          path: dist/Assemblies

      - name: "Pack"
        run: dotnet pack -c Release --no-build -o dist/NuGet

      - name: "Upload packages"
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }} NuGet Packages
          path: dist/NuGet
